name: pr-check

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: coriander

      - name: Initialize
        working-directory: coriander
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build firmware(minimal)
        working-directory: coriander
        run: |
          west build -b atk app -- -DCONFIG_CORIANDER_MINIMAL=y

      - name: Build manufaturor firmware
        working-directory: coriander
        run: |
          west build -b td2kw app -d build-manu --sysbuild
