name: pr-check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: coriander

      - name: Initialize
        working-directory: coriander
        run: |
          west init -l .
          west update

      - name: Build firmware
        working-directory: coriander
        run: |
          west build -b td2kw app
