name: release-publish

on:
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/zephyrproject-rtos/ci:v0.26.2 
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: coriander

      - name: Initialize
        working-directory: coriander
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Build firmware
        working-directory: coriander
        run: |
          west build -b td2kw app

      - name: Build manufatory firmware
        working-directory: coriander
        run: |
          west build -b td2kw app -d build-manu --sysbuild

      - name: Package firmware
        working-directory: coriander
        run: |
          mkdir -p firmware
          mkdir -p firmware/app
          mkdir -p firmware/bootloader
          rm build-manu/app/zephyr/*pre*
          cp build-manu/app/zephyr/zephyr.*.bin firmware/app
          rm build-manu/mcuboot/zephyr/*pre*
          cp build-manu/mcuboot/zephyr/zephyr.*.bin firmware/bootloader

      - name: Publish firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: coriander/firmware/
                  
